from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.create_table('users', sa.Column('id',sa.Integer(),nullable=False), sa.Column('email',sa.String(length=320),nullable=False), sa.Column('password_hash',sa.String(length=512),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('email'))
    op.create_index('ix_users_id','users',['id'],unique=False); op.create_index('ix_users_email','users',['email'],unique=False)
    op.create_table('user_profiles', sa.Column('id',sa.Integer(),nullable=False), sa.Column('user_id',sa.Integer(),nullable=False), sa.Column('full_name',sa.String(length=120)), sa.Column('leetcode_username',sa.String(length=100)), sa.Column('preferred_language',sa.String(length=50)), sa.Column('experience_level',sa.String(length=50)), sa.Column('target_role',sa.String(length=100)), sa.Column('bio',sa.String(length=180)), sa.Column('target_companies',sa.JSON()), sa.Column('preparation_timeline',sa.String(length=100)), sa.Column('onboarding_completed',sa.Boolean(),nullable=False), sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False), sa.ForeignKeyConstraint(['user_id'],['users.id'],ondelete='CASCADE'), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('user_id'))
    op.create_index('ix_user_profiles_id','user_profiles',['id'],unique=False); op.create_index('ix_user_profiles_user_id','user_profiles',['user_id'],unique=False)
    op.create_table('problems', sa.Column('id',sa.Integer(),nullable=False), sa.Column('slug',sa.String(length=120),nullable=False), sa.Column('title',sa.String(length=180),nullable=False), sa.Column('difficulty',sa.String(length=30),nullable=False), sa.Column('topics',sa.JSON(),nullable=False), sa.Column('description',sa.Text(),nullable=False), sa.Column('constraints',sa.JSON(),nullable=False), sa.Column('examples',sa.JSON(),nullable=False), sa.Column('test_cases',sa.JSON(),nullable=False), sa.Column('starter_code',sa.JSON(),nullable=False), sa.Column('source',sa.String(length=40),nullable=False), sa.Column('external_id',sa.String(length=120)), sa.Column('external_url',sa.String(length=500)), sa.Column('execution_mode',sa.String(length=20),nullable=False), sa.Column('time_limit_ms',sa.Integer(),nullable=False), sa.Column('memory_limit_mb',sa.Integer()), sa.Column('validation',sa.String(length=30),nullable=False), sa.Column('package_metadata',sa.JSON()), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('slug'))
    op.create_index('ix_problems_id','problems',['id'],unique=False); op.create_index('ix_problems_slug','problems',['slug'],unique=False); op.create_index('ix_problems_external_id','problems',['external_id'],unique=False)
    op.create_table('code_workspaces', sa.Column('id',sa.Integer(),nullable=False), sa.Column('user_id',sa.Integer(),nullable=False), sa.Column('problem_id',sa.Integer(),nullable=False), sa.Column('language',sa.String(length=50),nullable=False), sa.Column('code',sa.Text(),nullable=False), sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False), sa.ForeignKeyConstraint(['problem_id'],['problems.id'],ondelete='CASCADE'), sa.ForeignKeyConstraint(['user_id'],['users.id'],ondelete='CASCADE'), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('user_id','problem_id','language',name='uq_code_workspace_user_problem_language'))
    op.create_index('ix_code_workspaces_id','code_workspaces',['id'],unique=False); op.create_index('ix_code_workspaces_user_id','code_workspaces',['user_id'],unique=False); op.create_index('ix_code_workspaces_problem_id','code_workspaces',['problem_id'],unique=False)
    op.create_table('coding_attempts', sa.Column('id',sa.Integer(),nullable=False), sa.Column('user_id',sa.Integer(),nullable=False), sa.Column('problem_id',sa.Integer(),nullable=False), sa.Column('language',sa.String(length=50),nullable=False), sa.Column('mode',sa.String(length=20),nullable=False), sa.Column('code',sa.Text(),nullable=False), sa.Column('status',sa.String(length=50),nullable=False), sa.Column('summary',sa.String(length=255),nullable=False), sa.Column('results',sa.JSON(),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.ForeignKeyConstraint(['problem_id'],['problems.id'],ondelete='CASCADE'), sa.ForeignKeyConstraint(['user_id'],['users.id'],ondelete='CASCADE'), sa.PrimaryKeyConstraint('id'))
    op.create_index('ix_coding_attempts_id','coding_attempts',['id'],unique=False); op.create_index('ix_coding_attempts_user_id','coding_attempts',['user_id'],unique=False); op.create_index('ix_coding_attempts_problem_id','coding_attempts',['problem_id'],unique=False)
    op.create_table('mentor_sessions', sa.Column('id',sa.Integer(),nullable=False), sa.Column('user_id',sa.Integer(),nullable=False), sa.Column('problem_id',sa.Integer()), sa.Column('scope',sa.String(length=30),nullable=False), sa.Column('title',sa.String(length=180),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False), sa.ForeignKeyConstraint(['problem_id'],['problems.id'],ondelete='CASCADE'), sa.ForeignKeyConstraint(['user_id'],['users.id'],ondelete='CASCADE'), sa.PrimaryKeyConstraint('id'))
    op.create_index('ix_mentor_sessions_id','mentor_sessions',['id'],unique=False); op.create_index('ix_mentor_sessions_user_id','mentor_sessions',['user_id'],unique=False); op.create_index('ix_mentor_sessions_problem_id','mentor_sessions',['problem_id'],unique=False)
    op.create_table('mentor_messages', sa.Column('id',sa.Integer(),nullable=False), sa.Column('session_id',sa.Integer(),nullable=False), sa.Column('role',sa.String(length=20),nullable=False), sa.Column('content',sa.Text(),nullable=False), sa.Column('action',sa.String(length=30)), sa.Column('hint_level',sa.Integer()), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.ForeignKeyConstraint(['session_id'],['mentor_sessions.id'],ondelete='CASCADE'), sa.PrimaryKeyConstraint('id'))
    op.create_index('ix_mentor_messages_id','mentor_messages',['id'],unique=False); op.create_index('ix_mentor_messages_session_id','mentor_messages',['session_id'],unique=False)

def downgrade() -> None:
    op.drop_table('mentor_messages'); op.drop_table('mentor_sessions'); op.drop_table('coding_attempts'); op.drop_table('code_workspaces'); op.drop_table('problems'); op.drop_table('user_profiles'); op.drop_table('users')
